### ISSUE TITLE
Número mínimo aceitavel de examples para Intents

### ISSUE THREAD

**Issue by danielyudicarvalho** [danielyudicarvalho/sprint-5#13]
Segundo o padrão de desenvolvimento RASA, é recomendável ter no mínimo 6 examples para cada intent.
Também é bom evitar desequilibrio de examples. (Uma intent com 2 examples e outra intent com 50. Definir um número médio de examples).

**Comment by F-Camuso** [comment]
Fechando a issue pois com o PR #19 , esse problema é resolvido e futuramente o time vai se atentar a colocar no mínimo 6 exemplos
