### ISSUE TITLE
Inserir cinomose, parvovirose e doença do carrapato nas INF08

### ISSUE THREAD

**Issue by danielyudicarvalho** [danielyudicarvalho/sprint-5#18]

**Comment by danielyudicarvalho** [comment]
Atualizações de doenças cobertas pelo FAQ implementada na commit fbe4aadb1d0ba20a51d562eb988af8bef9b53fc3

**Comment by Leo0liveira** [comment]
Atende aos requisitos propostos, mas ainda é necessário adicionar a doença do carrapato.

**Comment by danielyudicarvalho** [comment]
doença adicionada
