### ISSUE TITLE
Implementar uma action para o greet

### ISSUE THREAD

**Issue by F-Camuso** [danielyudicarvalho/sprint-5#21]
Ao invés de deixar um greet estático, creio que seja melhor algo mais dinâmico, ex: "Bom dia/tarde/noite, usuário"
Para isso, sugiro criar uma action especifica para o greet  e usar o: `from datetime import datetime`, como o nosso usuário sempre vai ser campo grandense, só definir o timezone para Campo grande.

**Comment by jpwakugawa** [comment]
db9bb18 chore: implementando action_utter_greet

**Comment by Leo0liveira** [comment]
Atende aos requisitos solicitados, mas é necessário fazer a troca do nome "Caramelo".

Como sugestão, acho que a frase de saudação poderia ser "vamos ajudá-lo (a) a solucionar suas dúvidas" invés de "vamos te ajudar com as suas dúvidas" e também "Só para te alertar, eu posso falar sobre adoções, doenças, veterinários/castração, denúncias, também posso falar sobre resgate de pets ou te ajudar a achar o seu pet. " por "Eu posso te informar sobre as questões de adoção, doenças, veterinários, castração e denuncias. Posso também esclarecer dúvidas com relação a resgate de animais e também posso te ajudar a encontrar o pet".

**Comment by Leo0liveira** [comment]
Está atendendo os requisitos solicitados.
