### ISSUE TITLE
Implementar as novas respostas ao faq

### ISSUE THREAD

**Issue by F-Camuso** [danielyudicarvalho/sprint-5#22]
Fluxo usado como base: [FAQ 1](https://miro.com/app/board/uXjVOYD8DSo=/?moveToWidget=3458764516777424497&cot=14)

**Comment by jpwakugawa** [comment]
455e7c2 feat: adicionando fallback
1a9edf1 feat: faq/ask_how_to_adopt
3142ef6 feat: faq/ask_how_to_donate_animal
e6e0da6 feat: faq/ask_found_and_rescued
19cebb4 feat: faq/ask_lost_pet
d63e98a feat: faq/ask_need_rescue
c2d4b1e chore: melhorando formatação
72b70d2 chore: resolvendo conflitos

**Comment by Leo0liveira** [comment]
Atende aos requisitos, mas é possível adicionar mais exemplos de intenção.

**Comment by jpwakugawa** [comment]
abab612 chore: adicionando mais exemplos de intent

**Comment by Leo0liveira** [comment]
Está atendendo os requisitos solicitados.
