### ISSUE TITLE
Implementar as novas respostas ao FAQ

### ISSUE THREAD

**Issue by F-Camuso** [danielyudicarvalho/sprint-5#23]
Fluxo usado como base: [FAQ 2](https://miro.com/app/board/uXjVOYD8DSo=/?moveToWidget=3458764516777424607&cot=14)

**Comment by danielyudicarvalho** [comment]
atualização das respostas do FAQ implementado na commit fbe4aadb1d0ba20a51d562eb988af8bef9b53fc3

**Comment by Leo0liveira** [comment]
Está atendendo aos requisitos, mas sugiro alterar algumas frases, como:
- No arquivo responses.yml a frase "Sempre a seu dispor" por algo do tipo "Ao seu dispor" ou "Sempre ao seu dispor" e afins.
- No mesmo arquivo na parte de denúncias a frase "Vamos juntos diminuir o sofrimento animal. PARTICIPE!" trocar o participe por "Denuncie!".

**Comment by F-Camuso** [comment]
issue fechada pois o PR #30 e #27 resolve ela
