### ISSUE TITLE
Implementar busca no site procure1amigo [ADT01][ADT02]

### ISSUE THREAD

**Issue by F-Camuso** [danielyudicarvalho/sprint-5#24]
Usando a string `https://adotar.com.br/busca.aspx?cc=1484&cn=ms-campo-grande` como base, definir os outros parametros a partir do input do usuário, seguindo o formulário proposto no próprio link e depois retornando a string como um link para o usuário acessar a busca que ele fez.

**Comment by F-Camuso** [comment]
O fluxo a ser seguido é o adopt intent, que na verdade vamos mudar para search_intent, de ta maneira que fique mais claro o que o bot está fazendo
Link do fluxo: [Search_intent](https://miro.com/app/board/uXjVOYD8DSo=/?moveToWidget=3458764516859341212&cot=14)

**Comment by danielyudicarvalho** [comment]
funcionalidades ADOPT01 e ADOPT02 implementadas no commit: 951550f96e060b1cbb5eb280ea98eb2ad6f08a9f

**Comment by Leo0liveira** [comment]
Atende aos requisitos solicitados, só é necessário remover toxoplasmose da sessão "Diasease" visto que não cobrimos mais o escopo desta doença.

**Comment by F-Camuso** [comment]
Vou estar fechando essa issue pois o PR #30 e #27 já resolve ela
