### ISSUE TITLE
Implementar as features [DOA-1] até a [DOA-5]

### ISSUE THREAD

**Issue by F-Camuso** [danielyudicarvalho/sprint-5#25]
Após a reunião do dia 19/01 as 16:00, ficou decidido que o usuário irá passar pelo fluxo de doação/voluntariado, de tal forma que um email seja enviado para o Abrigo com as suas inteções e ao mesmo tempo ele recebe um link do whatapp da representante da ONG

Fluxo para ser usado como base: [Wanna help flow](https://miro.com/app/board/uXjVOYD8DSo=/?moveToWidget=3458764516961169499&cot=14)

**Comment by jpwakugawa** [comment]
175d398 chore: help_form enviando email com sucesso
982b4bc chore: padronizando help form
132af38 feat: volunteer_intent
6f15af7 chore: melhorando intents & legibilidade
650ede8 feat: wanna_help_flow

**Comment by Leo0liveira** [comment]
Atende aos requisitos propostos, sugiro adicionar mais exemplos nas intens

**Comment by jpwakugawa** [comment]
a54bb49 chore: adicionando exemplos nas intents
